servo_left:
  ros__parameters:
    planning_group_name: panda_arm
    command_in_type: pose
    pose_command_in_topic: /servo_left/pose_commands
    ee_frame_name: left_fr3_link6
    robot_link_command_frame: left_fr3_joint0
    publish_period: 0.01
    incoming_command_timeout: 0.1
    num_outgoing_halt_msgs_to_publish: 5
    lower_singularity_threshold: 15.0
    hard_stop_singularity_threshold: 30.0
    lower_collision_proximity_threshold: 0.1
    hard_stop_collision_proximity_threshold: 0.01
    joint_limit_margin: 0.1
    command_out_topic: /servo_joint_trajectory
    use_gazebo: false
    check_collisions: true
    collision_check_rate: 10
    robot_description: ""  
    robot_description_semantic: ""  
