# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - panda1_arm_controller
    - panda2_arm_controller
    - panda1_gripper_controller
    - panda2_gripper_controller

  panda1_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_finger_joint1
  panda2_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_finger_joint1
  panda1_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_finger_joint1
  panda2_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_finger_joint1
  panda1_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_fr3_finger_joint1
  panda2_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_fr3_finger_joint1