# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    panda1_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    panda2_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    panda1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    panda2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    panda1_gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    panda2_gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda1_arm_controller:
  ros__parameters:
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
panda2_arm_controller:
  ros__parameters:
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position

panda1_gripper_trajectory_controller:
  ros__parameters:
    joints:
      - left_fr3_finger_joint1
    
    command_interfaces:
      - position
      
    state_interfaces:
      - position
      - velocity
panda2_gripper_trajectory_controller:
  ros__parameters:
    joints:
      - right_fr3_finger_joint1
  
    command_interfaces:
      - position
     
    state_interfaces:
      - position
      - velocity