
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    panda1_arm_controller:
      type: fake_components/GenericSystem

    panda2_arm_controller:
      type: fake_components/GenericSystem

    panda1_controller:
      type: fake_components/GenericSystem

    panda2_controller:
      type: fake_components/GenericSystem

    panda1_gripper_controller:
      type: fake_components/GenericSystem

    panda2_gripper_controller:
      type: fake_components/GenericSystem

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda1_arm_controller:
  ros__parameters:
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_finger_joint1
    state_interfaces:
      - position
      - velocity

panda2_arm_controller:
  ros__parameters:
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_finger_joint1
    state_interfaces:
      - position
      - velocity

panda1_controller:
  ros__parameters:
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_finger_joint1
    state_interfaces:
      - position
      - velocity

panda2_controller:
  ros__parameters:
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_finger_joint1
    state_interfaces:
      - position
      - velocity

panda1_gripper_controller:
  ros__parameters:
    joints:
      - left_fr3_finger_joint1
    state_interfaces:
      - position
      - velocity

panda2_gripper_controller:
  ros__parameters:
    joints:
      - right_fr3_finger_joint1
    state_interfaces:
      - position
      - velocity